# Site settings
title: Z-car restore blog
email: 
description: Trying to restore a classic car
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vfusaro.github.io" # the base hostname & protocol for your site
github_username:  vfusaro

# Build settings
markdown: kramdown
permalink: pretty